pipeline {
  agent any

  environment {
    PROJECT_ID = 'your-gcp-project-id'  
    IMAGE_NAME = 'flask-app'
    IMAGE_TAG  = 'v1'
    GCR_IMAGE  = "gcr.io/${PROJECT_ID}/${IMAGE_NAME}:${IMAGE_TAG}"
  }

  stages {
 
    stage('Build Docker Image') {
      steps {
        dir('auto_remediate_platform/cicd-jenkins/') {
            script {
                sh "docker build -t ${GCR_IMAGE} ."
            }
        }
     }
    }

    stage('GCloud Auth') {
      steps {
        script {
          sh 'gcloud auth configure-docker --quiet'
        }
      }
    }

    stage('Push to GCR') {
      steps {
        script {
          sh "docker push ${GCR_IMAGE}"
        }
      }
    }

    stage('Verify Push') {
      steps {
        script {
          sh "gcloud container images list-tags gcr.io/${PROJECT_ID}/${IMAGE_NAME} --limit=1"
        }
      }
    }
  }
}

