apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-servicemonitor
  namespace: monitor
  labels:
    release: prom-stack
spec:
  selector:
    matchLabels:
      app: flask-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
