
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
  - hpa.yaml
  - ingress.yaml
  - prometheus-rules.yaml
  - flask-pdb.yaml

configMapGenerator:
  - name: flask-config
    literals:
      - FLASK_ENV=production
      - LOG_LEVEL=info