apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: app-alert-rules
  labels:
    release: prom-stack
spec:
  groups:
    - name: app.rules
      rules:
        - alert: HighPodCPUUsage
          expr: |
            sum(rate(container_cpu_usage_seconds_total{pod=~".*cpu-stress.*", container!="", container!="POD"}[1m]))
            by (pod) > 0.01
          for: 30s
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage on pod {{ $labels.pod }}"
            description: "Pod {{ $labels.pod }} is using more than 1% CPU for 30 seconds (for test)."

        - alert: PodRestartCountHigh
          expr: |
            increase(kube_pod_container_status_restarts_total[10m]) > 3
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "High pod restart count"
            description: "Pod {{ $labels.pod }} restarted more than 3 times in the last 10 minutes."
