pipeline {
  agent any

  options {
    timestamps()
    skipStagesAfterUnstable()
    timeout(time: 20, unit: 'MINUTES')
  }

  parameters {
    string(name: 'IMAGE_TAG', defaultValue: '', description: 'Override Docker image tag')
  }

  environment {
    PROJECT_ID   = 'master-project-504311'
    REGION       = 'asia-south1'
    CLUSTER_NAME = 'gke-cluster'
    IMAGE_NAME   = 'flask-app'
    AR_REPO      = 'docker-repo'
    TAG          = "${params.IMAGE_TAG ?: BUILD_NUMBER}"
    AR_IMAGE     = "${REGION}-docker.pkg.dev/${PROJECT_ID}/${AR_REPO}/${IMAGE_NAME}:${TAG}"
    K8S_NAMESPACE = 'production'
    DEPLOYMENT    = 'flask-app'
    CONTAINER     = 'flask-app'
  }

  stages {

    stage('Authenticate to GCP') {
      steps {
          sh '''
          set -e
          gcloud auth list
          gcloud config set project ${PROJECT_ID}
          gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet
          set -x
          '''
      }
    }

    stage('App Sanity Check') {
      steps {
        dir('app') {
          sh 'python3 -m py_compile src/app.py'
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        dir('app') {
          sh """
          docker build \
            --pull \
            --label git_commit=${GIT_COMMIT} \
            --label build_number=${BUILD_NUMBER} \
            -t ${AR_IMAGE} .
          """
        }
      }
    }

    stage('Scan Image with Trivy') {
      steps {
        sh """
        trivy image --exit-code 1 --severity HIGH,CRITICAL ${AR_IMAGE} || true
        """
      }
    }

    stage('Push Image to Artifact Registry') {
      steps {
        retry(2) {
          sh "docker push ${AR_IMAGE}"
        }
      }
    }

    stage('Deploy to GKE') {
      steps {
        sh """
        gcloud container clusters get-credentials ${CLUSTER_NAME} \
          --region ${REGION} \
          --project ${PROJECT_ID}

        kubectl set image deployment/${DEPLOYMENT} \
          ${CONTAINER}=${AR_IMAGE} \
          -n ${K8S_NAMESPACE}
        """
      }
    }

    stage('Verify Rollout') {
      steps {
        script {
          def status = sh(
            script: """
            kubectl rollout status deployment/${DEPLOYMENT} \
              -n ${K8S_NAMESPACE} \
              --timeout=120s
            """,
            returnStatus: true
          )

          if (status != 0) {
            echo "Rollout failed. Attempting rollback..."

            sh """
            kubectl rollout undo deployment/${DEPLOYMENT} \
              -n ${K8S_NAMESPACE}
            """

            error("Deployment failed and rollback executed.")
          }
        }
      }
    }
  }
}